### ISSUE TITLE
Remove contig hs37d5 from realignment/preprocessing

### ISSUE THREAD

**Issue by szilvajuhos** [SciLifeLab/CAW#80]
The contig hs37d5 is a decoy containing concatenated virus and similar sequences: http://www.cureffi.org/2013/02/01/the-decoy-genome/ Preprocessing it only eats up CPU and disk.

**Comment by szilvajuhos** [comment]
Looks we can exclude intervals by adding the -XL directive (https://software.broadinstitute.org/gatk/gatkdocs/org_broadinstitute_gatk_engine_CommandLineGATK.php#--excludeIntervals). So, I have put that into CreateIntervals (-XL hs37d5 ), and the run resumed from there.

**Comment by szilvajuhos** [comment]
Looks we have to remove from other steps as well to make processing shorter.

**Comment by szilvajuhos** [comment]
Also have to be removed from manta reference (and strelka)

**Comment by szilvajuhos** [comment]
Fixed for Manta, but put on hold for Strelka, as it is quite fast anyway.

**Comment by MaxUlysse** [comment]
cf #126 #127

**Comment by MaxUlysse** [comment]
Problem with Downsampled recalibrated data that still have this contig.
Since we only have recalibrated bams, and not the realigned bam files, realign should remove the contigs, but not sure, so I'm starting from fastq files.
